<%@ Page Title="" Language="C#" MasterPageFile="~/MY MASTER.master" AutoEventWireup="true" CodeFile="About_Us.aspx.cs" Inherits="About_Us" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div _designerregion="0">
    <asp:Image ID="Image1" runat="server" Height="187px" ImageUrl="~/MY IMAGES/CAU78PIP.jpg" Width="363px" />
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">It’s time! You’re ready to sell your textbooks, and you wisely made the decision to sell those textbooks to a buyback company. Selling textbooks may seem like a daunting task, but it doesn’t have to be. One of the first things you need to think about when you decide to sell textbooks is what condition your books are in.</span></p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        &nbsp;</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">If you look at your book, shrug, and think, “It looks fine, I guess,” we’re here to help you rate your book according to what buyback companies want to know. That way, when you sell textbooks, you’ll be presenting them in the most accurate manner possible.</span></p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        &nbsp;</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">Though it isn’t always the case, when you sell textbooks, many textbook buyback companies ask you to rate the condition of your book before they’ll give you a quote for what they are willing to pay. If you tell a buyback company your book is in good condition, but they feel otherwise when they receive it, they may send the textbook straight back to you. It’ll save a lot of time if you rate your textbook accurately so buyback companies can accept your book and pay you quickly.</span></p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        &nbsp;</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">Here are the top 5 most common phrases used to describe the condition of textbooks.</span></p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        &nbsp;</p>
    <h3 style="box-sizing: border-box; font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(75, 75, 75); margin-top: 20px; margin-bottom: 10px; font-size: 24px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">New</h3>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">You may have bought a textbook only to discover you actually needed a different one. If you want to sell textbooks that are in perfect condition, make sure you market them as such. This will help you get the most money back when you sell them. Rating a textbook as “</span><b style="box-sizing: border-box; font-weight: 700;">New</b><span style="box-sizing: border-box; font-weight: 400;">” means that it is literally<span class="Apple-converted-space">&nbsp;</span></span><b style="box-sizing: border-box; font-weight: 700;">new</b><span style="box-sizing: border-box; font-weight: 400;">–you didn’t use it, and no one used it before you.</span></p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <img alt="" class="alignright" height="414" src="https://bookscouter.com/img/blog/bookreview.png" style="box-sizing: border-box; border: 0px; vertical-align: middle; float: right; margin: 0px 0px 1em 1em;" width="276" /></p>
    <h3 style="box-sizing: border-box; font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(75, 75, 75); margin-top: 20px; margin-bottom: 10px; font-size: 24px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Like New</h3>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">This means your textbook is either in the same perfect condition it was when you purchased it, or it’s pretty close. You either barely used it or knew you would sell it at some point and made sure you took impeccable care of it. Good job!</span></p>
    <h3 style="box-sizing: border-box; font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(75, 75, 75); margin-top: 20px; margin-bottom: 10px; font-size: 24px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Very Good</h3>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">A book in “</span><b style="box-sizing: border-box; font-weight: 700;">very good</b><span style="box-sizing: border-box; font-weight: 400;">” condition means the pages aren’t torn and there isn’tt a volume of notes in the margins. The binding may be a little worn or the cover corners may be a little soft. This generally describes a book that has minimal signs of wear but nothing excessive.</span></p>
    <h3 style="box-sizing: border-box; font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(75, 75, 75); margin-top: 20px; margin-bottom: 10px; font-size: 24px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Good/Fair</h3>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">Your book still has all its pages, but the cover has seen better days. The binding isn’t nearly as pristine as it used to be, and you may be missing any CDs or other aides that came with the textbook. Your book is usable, but certainly doesn’t look new.</span></p>
    <h3 style="box-sizing: border-box; font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(75, 75, 75); margin-top: 20px; margin-bottom: 10px; font-size: 24px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Acceptable/Fine</h3>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <span style="box-sizing: border-box; font-weight: 400;">This textbook is significantly worn out. It has served many people well. There may be a lot of notes in the margins, highlights, ripped pages, coffee stains, a loose cover…basically, the book can be read, but it takes some effort.<span class="Apple-converted-space">&nbsp;</span></span><br style="box-sizing: border-box;" />
    </p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        &nbsp;</p>
    <p style="box-sizing: border-box; margin: 0px; color: rgb(75, 75, 75); font-family: 'Helvetica Neue', 'Open Sans', Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); height: 0px;">
        Using these guidelines, you should make sure you rate your books in the most accurate way possible when it comes time to sell them. Buyback companies will appreciate your honesty, and you’ll save yourself some time.</p>
</div>
</asp:Content>

