<%@ Page Language="C#" MasterPageFile="~/MY MASTER.master" AutoEventWireup="true" CodeFile="My Gallery.aspx.cs" Inherits="My_Gallery" Title="Untitled Page" validateRequest="false"  %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
   
     <style  type="text/css">         
            .hide
            {
            	 display:none;
            	 border-bottom-style:dotted;
            	 border-color:Red;
            	 border-bottom-width:3px;            	 
            }
            a          
             {
             	color:Red;
              }
            
            a:Hover .hide
            {
                 display:block;
                 position:relative;
                 top:-100px;
                 right:-100px;
                 width:100px;
                 height:150px;                                 
            }                    
    </style>

</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

     


    <table border="1px" >
       
        <tr>
            <td>Enter Item Name</td>
            <td colspan="2">
                <asp:TextBox runat="server" ID="txtname"></asp:TextBox>                
            </td>
        </tr>
        
        <tr>
            <td>Select Image:</td>
           <td>
                <asp:FileUpload runat="server" ID="fup" />
           </td>
            <td>
                <asp:Button runat="server" ID="btnupload" Text="Upload" 
                    onclick="btnupload_Click" />
            </td>
        </tr>                 
        <tr>
            <td colspan="3" align="center">
             <b>Album Photos</b>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <asp:DataList runat="server" ID="dst" RepeatColumns="3" BackColor="#FFFF66" 
                    BorderColor="#FF3300" BorderStyle="Solid" BorderWidth="2px" Width="443px" 
                    onselectedindexchanged="dst_SelectedIndexChanged">
                    <ItemTemplate>
                                <a href="<%#Eval("image")%>">
                            <i>
                                <asp:Image runat="server" ID="img" 
                                          ImageUrl='<%#Eval("image")%>'
                                          Width="100px" 
                                          BorderColor="green"
                                          BorderStyle="Solid"
                                          BorderWidth="3px"/>  
                                          </i>
                                          <i> 
                                          <img src='<%#Eval("image")%>'     
                                               runat="server" 
                                               id="img1" 
                                               class="hide" 
                                               alt="s" />                                                                               
                         
                            </i>
                            </a>
                             <br />
                            <i>
                           <asp:Label runat="server"  ID="lbl" Text='<%#Eval("name")%>'></asp:Label>
                            </i>
                    </ItemTemplate>
                </asp:DataList>
               
                <br />
            </td>
        </tr>
         <tr>
                <td colspan="2">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    AutoGenerateSelectButton="True" Caption="ALBUM RECORDS" CellPadding="4" 
                    DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" 
                    Width="441px" AllowPaging="True" DataKeyNames="id" PageSize="5">
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <Columns>
                        <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" 
                            ReadOnly="True" SortExpression="id" />
                        <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                        <asp:BoundField DataField="image" HeaderText="image" SortExpression="image" />
                    </Columns>
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
                </td>
                </tr>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:bookcon %>" SelectCommand="getall" 
                    SelectCommandType="StoredProcedure" DeleteCommand="album_del" 
            DeleteCommandType="StoredProcedure" UpdateCommand="album_update" 
            UpdateCommandType="StoredProcedure">
                    <DeleteParameters>
                        <asp:ControlParameter ControlID="GridView1" Name="id" 
                            PropertyName="SelectedValue" />
                    </DeleteParameters>
                    <UpdateParameters>
                        <asp:ControlParameter ControlID="GridView1" Name="name" 
                            PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="image" 
                            PropertyName="SelectedValue" />
                    </UpdateParameters>
        </asp:SqlDataSource>
      </table>
</asp:Content>

